<?php
namespace CanvaslyLite\Units;
if(!defined('ABSPATH')) exit;
class Grid extends Unit {
 public function type(){return 'grid';} public function title(){return __('Grid', 'canvasly-lite');} public function icon(){return "\u{25A6}";} public function category(){return 'layout';} public function supports_children(){return true;}
 public function defaults(){return ['columns'=>3,'rows'=>'','column_gap'=>20,'row_gap'=>20,'auto_flow'=>'row','align'=>'stretch','justify'=>'stretch','min_column'=>'120px','min_row'=>'auto','min_height'=>'','width'=>'100%','show_outline'=>false,'grid_template_columns'=>'','grid_template_rows'=>'','grid_auto_columns'=>'auto','grid_auto_rows'=>'auto','grid_auto_flow'=>'row','grid_auto_flow_dense'=>false];}
 public function controls(){return ['columns'=>'number','rows'=>'text','grid_template_columns'=>'text','grid_template_rows'=>'text','column_gap'=>'number','row_gap'=>'number','auto_flow'=>'select','align'=>'select','justify'=>'select','min_column'=>'text','min_row'=>'text','min_height'=>'text','grid_auto_columns'=>'text','grid_auto_rows'=>'text','show_outline'=>'switch','width'=>'text','grid_auto_flow'=>'select','grid_auto_flow_dense'=>'switch'];}
 public function render($s,$children=''){ $cols=max(1,min(24,absint($s['columns']??3)));$columns=trim($s['grid_template_columns']??'');if($columns==='')$columns='repeat('.$cols.',minmax('.esc_attr($s['min_column']??'0px').',1fr))';$rows=trim($s['grid_template_rows']??'');if($rows==='')$rows=trim(is_array($s['rows']??'')?'':(string)($s['rows']??''));if($rows!==''&&ctype_digit($rows))$rows='repeat('.max(1,min(24,(int)$rows)).',auto)';$flow=esc_attr($s['auto_flow']??$s['grid_auto_flow']??'row');$style='display:grid;grid-template-columns:'.$columns.';column-gap:'.absint(is_array($s['column_gap']??20)?($s['column_gap']['desktop']??20):($s['column_gap']??20)).'px;row-gap:'.absint(is_array($s['row_gap']??20)?($s['row_gap']['desktop']??20):($s['row_gap']??20)).'px;grid-auto-flow:'.$flow.';grid-auto-rows:'.esc_attr($s['grid_auto_rows']??$s['min_row']??'auto').';grid-auto-columns:'.esc_attr($s['grid_auto_columns']??'auto').';align-items:'.esc_attr($s['align']??'stretch').';justify-items:'.esc_attr($s['justify']??'stretch').';';
$minh=is_array($s['min_height']??'')?trim((string)($s['min_height']['desktop']??'')):trim((string)($s['min_height']??''));
if($minh!=='')$style.='min-height:'.esc_attr($minh).';';if($rows)$style.='grid-template-rows:'.esc_attr($rows).';';$cl=$this->cls($s).' lb-grid';if(!empty($s['show_outline']))$cl.=' lb-grid-outline';return '<div class="'.esc_attr($cl).'" style="'.$style.'">'.$children.'</div>'; }
}
